### ISSUE TITLE
Client example

### ISSUE THREAD

**Issue by HaydenMeloche** [anwfr/stomp-user-example#1]
Hi :)
I was wondering if you had an example of a client side call to this websocket. I'm fairly new to websockets and don't really understand how you can pass a map to the /register endpoint. 

After registering does the client then open to /connect and subscribe to the queue endpoint?

Thanks for your time.

**Comment by anwfr** [comment]
hello,

have a look to stomp-user-example/src/test/java/fr/anw/stompUserExample/server/WsConfigIntegrationTest.java for client example

client connects to /connect, then subscribes to /queue (to receive updates from there)
for each client sending to /register, subscribed clients will get updates at /queue (broadcast) and sending client will get a private reply at /private/queue
